/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bakery.app.ui;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author WIN 10
 */
public class BakeryAppJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BakeryAppJFrame
     */
    public BakeryAppJFrame() {
        initComponents();
        PanelTrangChu trangChu = new PanelTrangChu();
        PanelBanHang banHang = new PanelBanHang();
        PanelThongKe thongKe = new PanelThongKe();
        PanelBanh banh = new PanelBanh();
        PanelLichSu lichSu = new PanelLichSu();
        PanelLoaiBanh loaiBanh = new PanelLoaiBanh();
        PanelNhanVien nhanVien = new PanelNhanVien();
        PanelHoSo hoSo = new PanelHoSo();

        mainPanel.add(trangChu, "trangchu");
        mainPanel.add(banHang, "banhang");
        mainPanel.add(thongKe, "thongke");
        mainPanel.add(banh,"banh");
        mainPanel.add(lichSu,"lichsu");
        mainPanel.add(nhanVien,"nhanvien");
        mainPanel.add(loaiBanh,"loaibanh");
        mainPanel.add(hoSo,"hoso");
        //  Hiện trang chủ đầu tiên
    CardLayout cl = (CardLayout) mainPanel.getLayout();
    cl.show(mainPanel, "trangchu");
        lblProfile.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Đổi icon con trỏ thành tay

lblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        // Xử lý khi click vào "Truy cập hồ sơ"
        
        
        // Hoặc mở JDialog / JPanel hiển thị hồ sơ
        // new HoSoDialog(this, true).setVisible(true);
    }
});
        // Tạo viền nổi và viền lỗm
Border normal = BorderFactory.createRaisedBevelBorder();
Border hover = BorderFactory.createLoweredBevelBorder();

// Gắn mặc định là nổi
pntrangchu.setBorder(normal);
pnbanhang.setBorder(normal);
pnlichsu.setBorder(normal);
pnqlbanh.setBorder(normal);
pnqlloaibanh.setBorder(normal);
pnthongke.setBorder(normal);
pnnhanvien.setBorder(normal);

// Hàm gắn hiệu ứng hover
addHoverEffect(pntrangchu, normal, hover);
addHoverEffect(pnbanhang, normal, hover);
addHoverEffect(pnlichsu, normal, hover);
addHoverEffect(pnqlbanh, normal, hover);
addHoverEffect(pnqlloaibanh, normal, hover);
addHoverEffect(pnthongke, normal, hover);
addHoverEffect(pnnhanvien, normal, hover);
        showDateTime();
       
    setTitle("BakeryApp");
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    setSize(screenSize);
    setExtendedState(JFrame.MAXIMIZED_BOTH);

    JPanel mainPanel = new JPanel(new BorderLayout());
    }
    public void showDateTime() {
    Timer timer = new Timer(1000, e -> {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String currentTime = sdf.format(new Date());
        Timer.setText(currentTime); // dùng tên biến của bạn
    });
    timer.start();
}
    private void addHoverEffect(JPanel panel, Border normal, Border hover) {
    panel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            panel.setBorder(hover);
            panel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            panel.setBorder(normal);
        }
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnnhanvien = new javax.swing.JPanel();
        pnthongke = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnqlloaibanh = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnqlbanh = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlichsu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnbanhang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pntrangchu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        pnnhanvien.setBackground(new java.awt.Color(153, 204, 255));
        pnnhanvien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnnhanvienMouseClicked(evt);
            }
        });

        pnthongke.setBackground(new java.awt.Color(153, 204, 255));
        pnthongke.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnthongkeMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thống kê");

        javax.swing.GroupLayout pnthongkeLayout = new javax.swing.GroupLayout(pnthongke);
        pnthongke.setLayout(pnthongkeLayout);
        pnthongkeLayout.setHorizontalGroup(
            pnthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnthongkeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        pnthongkeLayout.setVerticalGroup(
            pnthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnthongkeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnqlloaibanh.setBackground(new java.awt.Color(153, 204, 255));
        pnqlloaibanh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnqlloaibanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnqlloaibanhMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(153, 204, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quản lí loại bánh");

        javax.swing.GroupLayout pnqlloaibanhLayout = new javax.swing.GroupLayout(pnqlloaibanh);
        pnqlloaibanh.setLayout(pnqlloaibanhLayout);
        pnqlloaibanhLayout.setHorizontalGroup(
            pnqlloaibanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnqlloaibanhLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnqlloaibanhLayout.setVerticalGroup(
            pnqlloaibanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnqlloaibanhLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnqlbanh.setBackground(new java.awt.Color(153, 204, 255));
        pnqlbanh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnqlbanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnqlbanhMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quản lí bánh");

        javax.swing.GroupLayout pnqlbanhLayout = new javax.swing.GroupLayout(pnqlbanh);
        pnqlbanh.setLayout(pnqlbanhLayout);
        pnqlbanhLayout.setHorizontalGroup(
            pnqlbanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnqlbanhLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnqlbanhLayout.setVerticalGroup(
            pnqlbanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnqlbanhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlichsu.setBackground(new java.awt.Color(153, 204, 255));
        pnlichsu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlichsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlichsuMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(153, 204, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lịch sử bán hàng");

        javax.swing.GroupLayout pnlichsuLayout = new javax.swing.GroupLayout(pnlichsu);
        pnlichsu.setLayout(pnlichsuLayout);
        pnlichsuLayout.setHorizontalGroup(
            pnlichsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlichsuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlichsuLayout.setVerticalGroup(
            pnlichsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlichsuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnbanhang.setBackground(new java.awt.Color(153, 204, 255));
        pnbanhang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnbanhangMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bán hàng");

        javax.swing.GroupLayout pnbanhangLayout = new javax.swing.GroupLayout(pnbanhang);
        pnbanhang.setLayout(pnbanhangLayout);
        pnbanhangLayout.setHorizontalGroup(
            pnbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbanhangLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnbanhangLayout.setVerticalGroup(
            pnbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbanhangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pntrangchu.setBackground(new java.awt.Color(153, 204, 255));
        pntrangchu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pntrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pntrangchuMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trang chủ");

        javax.swing.GroupLayout pntrangchuLayout = new javax.swing.GroupLayout(pntrangchu);
        pntrangchu.setLayout(pntrangchuLayout);
        pntrangchuLayout.setHorizontalGroup(
            pntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntrangchuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pntrangchuLayout.setVerticalGroup(
            pntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntrangchuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhân viên");

        javax.swing.GroupLayout pnnhanvienLayout = new javax.swing.GroupLayout(pnnhanvien);
        pnnhanvien.setLayout(pnnhanvienLayout);
        pnnhanvienLayout.setHorizontalGroup(
            pnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnqlloaibanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnqlbanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlichsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnbanhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pntrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnnhanvienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        pnnhanvienLayout.setVerticalGroup(
            pnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnnhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pntrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnbanhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlichsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnqlbanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnqlloaibanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnthongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(pnnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        lblProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblProfile.setText("Truy cập hồ sơ");
        lblProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProfileMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Usutxt");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("- nv/ql");

        Timer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Timer.setForeground(new java.awt.Color(255, 255, 255));
        Timer.setText("dd/MM/yyyy HH:mm:ss");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(46, 46, 46)
                .addComponent(lblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 550, Short.MAX_VALUE)
                .addComponent(Timer, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Timer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(new javax.swing.border.MatteBorder(null));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pntrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pntrangchuMouseClicked
       CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "trangchu");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_pntrangchuMouseClicked

    private void pnbanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnbanhangMouseClicked
        CardLayout cl = (CardLayout) mainPanel.getLayout();
    cl.show(mainPanel, "banhang");
// TODO add your handling code here:
    }//GEN-LAST:event_pnbanhangMouseClicked

    private void pnthongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnthongkeMouseClicked
        CardLayout cl = (CardLayout) mainPanel.getLayout();
    cl.show(mainPanel, "thongke");
// TODO add your handling code here:
    }//GEN-LAST:event_pnthongkeMouseClicked

    private void pnqlbanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnqlbanhMouseClicked
        CardLayout cl = (CardLayout) mainPanel.getLayout();
    cl.show(mainPanel, "banh");
        // TODO add your handling code here:
    }//GEN-LAST:event_pnqlbanhMouseClicked

    private void pnlichsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlichsuMouseClicked
        CardLayout cl = (CardLayout) mainPanel.getLayout();
    cl.show(mainPanel, "lichsu");
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlichsuMouseClicked

    private void pnqlloaibanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnqlloaibanhMouseClicked
    CardLayout cl = (CardLayout) mainPanel.getLayout();
    cl.show(mainPanel, "loaibanh");
// TODO add your handling code here:
    }//GEN-LAST:event_pnqlloaibanhMouseClicked

    private void pnnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnnhanvienMouseClicked
CardLayout cl = (CardLayout) mainPanel.getLayout();
    cl.show(mainPanel, "nhanvien");
        // TODO add your handling code here:
    }//GEN-LAST:event_pnnhanvienMouseClicked

    private void lblProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfileMouseClicked
CardLayout cl = (CardLayout) mainPanel.getLayout();
    cl.show(mainPanel, "hoso");
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new BakeryAppJFrame());
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BakeryAppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BakeryAppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BakeryAppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BakeryAppJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BakeryAppJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Timer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnbanhang;
    private javax.swing.JPanel pnlichsu;
    private javax.swing.JPanel pnnhanvien;
    private javax.swing.JPanel pnqlbanh;
    private javax.swing.JPanel pnqlloaibanh;
    private javax.swing.JPanel pnthongke;
    private javax.swing.JPanel pntrangchu;
    // End of variables declaration//GEN-END:variables
}
